package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26-dev

import (
	"context"

	"github.com/Desuuuu/gqlgen-optional-test/graph/model"
)

// Foo is the resolver for the foo field.
func (r *queryResolver) Foo(ctx context.Context, input model.FooInput) (string, error) {
	return input.String(), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
