// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type FooInput struct {
	Text graphql.Optional[*string] `json:"text,omitempty"`
}
